version: 0.2

phases:
  # install:
  #   commands:
  #     - pip install awscli

  build:
    commands:
      - zip lambda-function.zip lambda_function.py
      - mkdir -p package/python
      - "pip install --platform manylinux2014_aarch64 --target=package/python --implementation cp --python-version 3.11 --only-binary=:all: --upgrade -r requirements.txt"
      - cd package
      - zip -r ../lambda-layer.zip .
      - cd ..

  post_build:
    commands:
      - aws s3 cp lambda-function.zip s3://alpaca-trading-algo/lambda-function.zip
      - aws s3 cp lambda-layer.zip s3://alpaca-trading-algo/lambda-layer.zip
      - LAYER_VERSION_ARN=$(aws lambda publish-layer-version --layer-name dependencies --description "Dependencies Layer" --content S3Bucket=alpaca-trading-algo,S3Key=lambda-layer.zip --compatible-runtimes python3.11 | jq -r ".LayerVersionArn")
      - aws lambda update-function-code --function-name AlpacaTradingAlgo --s3-bucket alpaca-trading-algo --s3-key lambda-function.zip
      - aws lambda update-function-configuration --function-name AlpacaTradingAlgo --layers $LAYER_VERSION_ARN

artifacts:
  files:
    - lambda-function.zip
    - lambda-layer.zip
  discard-paths: yes
