AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: "MyAlpacaTradingLayer"
      Content:
        S3Bucket: alpaca-trading-algo
        S3Key: lambda-layer.zip
      CompatibleRuntimes:
        - python3.11

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "MyAlpacaTradingFunction"
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: alpaca-trading-algo
        S3Key: lambda-function.zip
      Runtime: python3.11
      Layers:
        - !Ref LambdaLayer
      Timeout: 30
      MemorySize: 128

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Policies:
        - PolicyName: "LambdaExecutionPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "logs:*"
                  - "cloudwatch:*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                Resource:
                  - !Sub "arn:aws:s3:::alp  a-trading-algo/*"
