version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python main.py
          name: main

workflows:
  hourly-schedule:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build-and-test

  build-on-push:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main