name: Scheduled Run

on:
  schedule:
    # 10 minutes before pre-market opens (3:50 AM EST -> 8:50 AM UTC)
    - cron: '50 8 * * *'
    # 10 minutes before market opens (9:30 AM EST -> 2:20 PM UTC)
    - cron: '20 14 * * *'
    # Mid-day check (11:50 AM EST -> 4:50 PM UTC)
    - cron: '50 16 * * *'
    # 15 minutes before market closes (3:45 PM EST -> 8:45 PM UTC)
    - cron: '45 20 * * *'
    # 10 minutes before post-market closes (7:50 PM EST -> 12:50 AM UTC next day)
    - cron: '45 0 * * *'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assuming you have a requirements.txt file

    - name: Run the program
      run: python main.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SLACK_API: ${{ secrets.SLACK_API }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
