name: Scheduled Run

on:
  schedule:
    # Market Open (9:30 AM EST -> 2:30 PM UTC), Monday to Friday
    - cron: '30 14 * * 1-5'
    # Mid-day check (12:00 PM EST -> 5:00 PM UTC), Monday to Friday
    - cron: '0 17 * * 1-5'
    # 15 minutes before market closes (3:45 PM EST -> 8:45 PM UTC), Monday to Friday
    - cron: '45 20 * * 1-5'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assuming you have a requirements.txt file
    
    - name: Download last-run-timestamp artifact
      uses: actions/download-artifact@v2
      with:
        name: last-run-timestamp
    - name: Read TIMESTAMP
      run: |
        if [ -f TIMESTAMP ]; then
          export LAST_RUN_TIMESTAMP=$(cat TIMESTAMP)
        else
          export LAST_RUN_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ" --date='1 hour ago')
        fi
  
    - name: Run the program
      run: python main.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SLACK_API: ${{ secrets.SLACK_API }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

    - name: Save current timestamp
      run: |
        echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" > TIMESTAMP
    - name: Upload TIMESTAMP as artifact
      uses: actions/upload-artifact@v2
      with:
        name: last-run-timestamp
        path: TIMESTAMP
  