name: Scheduled Run

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: Default

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assuming you have a requirements.txt file

    - name: Run the program
      run: python main.py
